$load test/apply.m
$clear

// TODO uncomment once await/awaits are clean
//$load test/await.m
//$clear
//$load test/awaits.m
//$clear

$load test/cbuf.m
$clear

// TODO uncomment or remove permanently
//$load test/circwatch.m
//$clear

$load test/decompa.m
$clear
$load test/inlineparams.m
$clear
$load test/livelock.m
$clear
$load test/msort.m
$clear

// TODO test currently causes a fatal error (by design)
// $load test/nesting.m
// $clear

$load test/newtype.m
$clear
$load test/pc.m
$clear
$load test/rle.m
$clear
$load test/qsort.m
$clear
$load test/regress.m
$clear
$load test/starvation.m
$clear
$load test/starvation2.m
$clear
$load test/tagpair.m
$clear
$load test/test_intrinsics.m
$clear
$load test/test_library.m
$clear
$load test/tranfuncs.m
$clear
$load test/transtress.m
$clear
$load test/type_anno.m
$clear
$load test/test_imports.m
$quit
